# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Califo

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [3]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [4]:
from sklearn.linear_model import LinearRegression
linb = LinearRegression()

In [5]:
linb.fit(X_train, y_train)

LinearRegression()

In [6]:
y_pred_test_set = linb.predict(X_test)

In [7]:
y_pred_train_set = linb.predict(X_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [8]:
from sklearn import metrics

In [9]:
r2_test = metrics.r2_score(y_test, y_pred_test_set)
r2_test

0.707618048495992

In [10]:
r2_train = metrics.r2_score(y_train, y_pred_train_set)
r2_train

0.7458842074387575

## 4. Calculate and print mean squared error for both the training and the testing set.

In [11]:
MSE_test = metrics.mean_squared_error(y_test,y_pred_test_set)
MSE_test

19.864238966896

In [12]:
MSE_train = metrics.mean_squared_error(y_train ,y_pred_train_set)
MSE_train

22.504833672882476

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [13]:
MAE_test = metrics.mean_absolute_error(y_test ,y_pred_test_set)
MAE_test

3.223740566157909

In [14]:
MAE_train = metrics.mean_absolute_error(y_train ,y_pred_train_set)
MAE_train

3.3038964363848717

## Classification Model Evaluation

In [15]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [16]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lreg = LogisticRegression()

In [19]:
lreg.fit(X_train, y_train)

/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
y_pred_test = lreg.predict(X_test)
y_pred_test

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 1, 0, 2, 1, 0, 1, 0, 1,
       0, 2, 1, 2, 2, 0, 1, 1])

In [21]:
y_pred_train = lreg.predict(X_train)
y_pred_train

array([2, 1, 2, 1, 2, 1, 2, 2, 0, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 2, 2, 2, 0, 2, 0, 1, 2, 0, 1, 1, 2, 2, 0, 0, 2, 0, 2, 1, 1,
       0, 2, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 1, 1, 1, 2, 0, 0, 2, 0, 0,
       2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0,
       1, 2, 1, 0, 0, 2, 2, 1, 2, 0, 2, 0, 2, 2, 2, 0, 1, 1, 2, 0, 1, 0,
       2, 2, 1, 0, 2, 2, 1, 1, 0, 1])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [22]:
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score, recall_score, f1_score, fbeta_score, confusion_matrix


In [23]:
acctest = accuracy_score(y_test, y_pred_test)
acctest

1.0

In [24]:
acctrain = accuracy_score(y_train, y_pred_train)
acctrain

0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [25]:
bacctest = balanced_accuracy_score(y_test, y_pred_test)
bacctest

1.0

In [26]:
bacctrain = balanced_accuracy_score(y_train, y_pred_train)
bacctrain

0.9668699186991869

## 10. Calculate and print the precision score for both the training and the testing set.

In [27]:
prectest = precision_score(y_test, y_pred_test, average='macro')
prectest

1.0

In [28]:
prectrain = precision_score(y_train, y_pred_train, average='macro')
prectrain

0.9679722562219503

## 11. Calculate and print the recall score for both the training and the testing set.

In [29]:
rectest = recall_score(y_test, y_pred_test, average='macro')
rectest

1.0

In [30]:
rectrain = recall_score(y_train, y_pred_train, average='macro')
rectrain

0.9668699186991869

## 12. Calculate and print the F1 score for both the training and the testing set.

In [31]:
f1test = f1_score(y_test, y_pred_test, average='macro')
f1test

1.0

In [32]:
f1train = f1_score(y_train, y_pred_train, average='macro')
f1train

0.9670329670329672

## 13. Generate confusion matrices for both the training and the testing set.

In [33]:
confusion_matrix(y_train, y_pred_train)

array([[39,  0,  0],
       [ 0, 37,  3],
       [ 0,  1, 40]])

In [34]:
confusion_matrix(y_test, y_pred_test)

array([[11,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  9]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

# For numeric distributions, Boston dataset

In [35]:
from sklearn.linear_model import Ridge, Lasso

from sklearn.linear_model import SGDRegressor

from sklearn.neighbors import KNeighborsRegressor

from sklearn.ensemble import GradientBoostingRegressor

from sklearn.svm import SVR

In [36]:
modelsn={
    'ridge': Ridge(),
    'lasso': Lasso(),
    'sgd': SGDRegressor(),
    'knn': KNeighborsRegressor(),
    'grad': GradientBoostingRegressor(),
}

In [37]:
data = load_boston()
X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Califo

In [38]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

In [39]:
for name, model in modelsn.items():
    print("Training: ", name)
    model.fit(X_train, y_train)

/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training:  ridge
Training:  lasso
Training:  sgd
Training:  knn
Training:  grad


In [40]:
for name, model in modelsn.items():
    y_pred = model.predict(X_test)
    print(f"------{name}------")
    print('MAE - ', metrics.mean_absolute_error(y_test, y_pred))
    print('MSE - ', metrics.mean_squared_error(y_test, y_pred))
    print('RMSE - ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
    print('R2 - ', metrics.r2_score(y_test, y_pred))

------ridge------
MAE -  3.9853896934256885
MSE -  35.897268737651764
RMSE -  5.99143294526875
R2 -  0.6100986951745855
------lasso------
MAE -  4.654559620860394
MSE -  42.80972825884894
RMSE -  6.542914355151605
R2 -  0.5350184152077497
------sgd------
MAE -  117538174405089.2
MSE -  1.4811382481104296e+28
RMSE -  121702023323789.88
R2 -  -1.6087511832323936e+26
------knn------
MAE -  5.266862745098041
MSE -  55.67623921568627
RMSE -  7.461651239215504
R2 -  0.3952676880066157
------grad------
MAE -  2.1164150889730813
MSE -  8.226073266389387
RMSE -  2.8681131892569
R2 -  0.9106517901516401


# For classifier distributions (iris dataset)

In [41]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier

In [42]:
#your code
modelsc={
    'dis': LinearDiscriminantAnalysis(),
    'neighbors': KNeighborsClassifier(),
    'naive': GaussianNB(),
    'tree': DecisionTreeClassifier(),
    'svm': SVC(),
    'qua' : QuadraticDiscriminantAnalysis(),
    'ranfo' : RandomForestClassifier(),
    'adab' : AdaBoostClassifier(),
    'mlp' :MLPClassifier()
}

In [43]:
data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [44]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

In [45]:
for name, model in modelsc.items():
    print("training ", name)
    model.fit(X_train,y_train)

training  dis
training  neighbors
training  naive
training  tree
training  svm
training  qua
training  ranfo


/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y 

training  adab
training  mlp


/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/andrestart/anaconda3/envs/iron/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [46]:
for name, model in modelsc.items():
    y_pred = model.predict(X_test)
    print(f"--------{name}--------")
    print("Accuracy: ", accuracy_score(y_test,y_pred))
    print("Precision: ", precision_score(y_test,y_pred, average='micro'))
    print("Recall: ", recall_score(y_test,y_pred, average='micro'))
    print("F1: ", f1_score(y_test, y_pred, average='micro'))

--------dis--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------neighbors--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------naive--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------tree--------
Accuracy:  0.9666666666666667
Precision:  0.9666666666666667
Recall:  0.9666666666666667
F1:  0.9666666666666667
--------svm--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------qua--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------ranfo--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------adab--------
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0
--------mlp--------
Accuracy:  0.9666666666666667
Precision:  0.9666666666666667
Recall:  0.9666666666666667
F1:  0.9666666666666667
